---
title: "Stat 331 Final Project"
author: "Curtis LeQuang, Warren Woo, Johnny Young, Carter Coppes"
format: 
  html:
    embed-resources: true
    code-tools: true
    toc: true
editor: source
execute: 
  error: true
  echo: true
  message: false
  warning: false
---

```{r setup}
#| code-fold: true
library(tidyverse)
library(here)

GDP <- read.csv(here::here("gdp_pcap.csv"))
income <- read.csv(here::here("mincpcap_cppp.csv"))
```

```{r data cleaning pt1}
#| code-fold: true
GDP_cleaned <- GDP |>
  rename_all(~ str_remove(., "^X")) |>
  mutate(across('1800':'2100', ~ as.numeric(str_replace_all(., "k", "e3")))) |>
  pivot_longer(cols = '1800':'2100',
               names_to = "Year",
               values_to = "GDP per capita ($)")
```

```{r data cleaning pt2}
#| code-fold: true
income_cleaned <- income |>
  rename_all(~ str_remove(., "^X")) |>
  mutate(across('1800':'2100', ~ as.numeric(str_replace_all(., "k", "e3")))) |>
  pivot_longer(cols = '1800':'2100',
               names_to = "Year",
               values_to = "Average Daily Income ($)")
```

```{r data joining}
#| code-fold: true
project_data <- inner_join(GDP_cleaned, income_cleaned)

project_data <- project_data |>
  group_by(country) |>
  summarize(across(where(is.numeric), mean, na.rm=TRUE))
```

```{r data visualization #2}
#| code-fold: true
  ggplot(project_data, aes(x = `Average Daily Income ($)`, 
                           y = `GDP per capita ($)`)) +
    geom_bin2d() +
    scale_fill_viridis_c() +
    labs(x = "Average Daily Income ($)",
         y = "GDP per capita ($)",
         fill = "Density") +
    theme_bw()
  ```
```

```{r linear regression}
#| code-fold: true
project_data_lm <- lm(`GDP per capita ($)` ~ `Average Daily Income ($)`,
                        data = project_data)
  
broom::tidy(project_data_lm)
```
**let y = GDP per capita and let x = average daily income
-> y = 290.62 + 890.4x
  
Given this linear equation, if a given country were to have an average daily income over the years of 0, their average GDP per capita over the years would be about 290.62. Furthermore, the expected change in average GDP per capita over the years is about 890.4 when average daily income over the years increases by 1 unit.**
    
```{r model fit}
#| code-fold: true
summary(project_data_lm)
  
ii
```